### ISSUE TITLE
Finomhangold a designt

### ISSUE THREAD

**Issue by Pondzsi** [Pondzsi/moovie-app-js#10]
Finomhangold a designt a layout valtoztasa nelkul (vagy csak keveset ha muszaly)
- Az elemek szinkodjai (hex) ??
- Hasznalando betutipusok (hol melyiket) ?? -> https://fonts.google.com/ (innen valasz kerlek)
- Amikor a kezdolapon ra hover-elsz (raviszed a kurzort) egy film kartyara milyen kicsi de vagany efektet mutathatunk?
  - lehetoleg valamilyen keppen jelenjen meg a film cime is valamilyen keppen (vannak olyan kepek is amiben nincs benne a film cime)
  - peldak hover-effectre https://uimovement.com/tag/hover/

**Comment by miholcsa** [comment]
[colour, font, animáció.docx](https://github.com/Pondzsi/moovie-app-js/files/5244806/colour.font.animacio.docx)
