### ISSUE TITLE
Tudjunk keresni filmre (backend)

### ISSUE THREAD

**Issue by Pondzsi** [Pondzsi/moovie-app-js#17]
- legyen onChange -el megoldva de legyen delay 700ms-1s ahogy jobban erzed

- az index.js fajlban legyen

### szukseges info:
- cim,leiras,foto,rendezo

**Comment by Hudumannaia** [comment]
Az api "id, logo_path, name" (+origin_country) mezoket kuld vissza, ki kene nyerni tobbet egy-egy filmrol?

**Comment by Hudumannaia** [comment]
+ csinaétam egy hibat hogy a masterben dolgoztam, bocsi
+ rajottem mire is jo a (tobb) commit meg

**Comment by Pondzsi** [comment]
Csinald ugy hogy eleg lesz ennyi mert a tobb adatot ugy kell hogy egy uj api kerest adsz az ID-val, de azt nem akarjuk minden billentyulenyomasnal tobszor is megismetelni!

**Comment by Hudumannaia** [comment]
Tudom, hogy ugy kene, ezért is kérdeztem. Akkor Task is done!

**Comment by Pondzsi** [comment]
- nem volt pullrequest -> most van a masterben olyan fejlesztes amit nem lehet egy felhasznalonak megmutatni, elre oda kell figyelni, ha latod hogy nem perfekt ne ragd fel a masterbe csinalgy egy PullRequestet, le ellenorizzuk es oda irjuk hogy szerintunk mi a gond.
- az api keres amit csinaltal az azert nem mukodik ugy ahogy te szeretned mert nem jo az url, te cegeket keresel nem pedig filmeket az adatbazisban! 
- Jo api keres info: https://developers.themoviedb.org/3/search/search-movies -> itt megtalalod a jo URL-t

**Comment by Hudumannaia** [comment]
Menjen a porno is bele? (include_adult isTrue?)

**Comment by Hudumannaia** [comment]
rendezot nem talalom

**Comment by Hudumannaia** [comment]
Van egy branchem, légyszi akkor nézz rá Pongi, rakok is PRt rá (Áh elfelejtettem.. nem tudok. Branchet még létre tudtam hozni, s nem merek a merge request-el kísérletezni)

**Comment by Pondzsi** [comment]
@Hudumannaia megcsinaltam a designt a keresesnek.
 - megkerlek old meg azt hogy amikor van film amire rakerestunk akkor a 
#search-result hoz adj hozza egy classt (.search-result-border) es amikor nincs akkor vedd le rola.
 - ez azert kell mert igy nezz ki ha alapbol rajta van es nincs egy film sem.
![image](https://user-images.githubusercontent.com/48091111/93737450-ed93e380-fbeb-11ea-98e7-cd199ad3947f.png)

https://stackoverflow.com/questions/6787383/how-to-add-remove-a-class-in-javascript

**Comment by Pondzsi** [comment]
Another solution made for this
