### ISSUE TITLE
Mappeld at html be es jelenitsd meg az adatot amikor keresel

### ISSUE THREAD

**Issue by Pondzsi** [Pondzsi/moovie-app-js#19]
Mappeld at html be es jelenitsd meg az adatot amikor keresel

**Comment by Hudumannaia** [comment]
Kind of kesz, de majd meg kell korepetalas (pl cssben is). Nem 100% a task, de lehet tovabb vele dolgozni, szoval done

**Comment by Pondzsi** [comment]
@Hudumannaia megcsinaltam a designt a keresesnek.
 - megkerlek old meg azt hogy amikor van film amire rakerestunk akkor a 
#search-result hoz adj hozza egy classt (.search-result-border) es amikor nincs akkor vedd le rola.
 - ez azert kell mert igy nezz ki ha alapbol rajta van es nincs egy film sem.
![image](https://user-images.githubusercontent.com/48091111/93737450-ed93e380-fbeb-11ea-98e7-cd199ad3947f.png)

https://stackoverflow.com/questions/6787383/how-to-add-remove-a-class-in-javascript
